Django/StockAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.main, name='main'),
    path('corperations/', views.corperations, name='corperations'),
    path('readexcel/', views.read_excel, name='read_excel'),
    path('readdata/', views.read_data, name='read_data'),
    path('analyzeddata/', views.analyzed_data, name='analyzed_data'),
]

Django/articles/models.py
from django.db import models

# Create your models here.
class Stocks(models.Model):
    code = models.CharField(max_length=10)
    date = models.DateField()
    tradePrice = models.IntegerField()
    openingPrice = models.IntegerField()
    candleAccTradeVolume = models.IntegerField()
    changePrice = models.IntegerField()
    changeRate = models.FloatField()


class Stock_Analyze(models.Model):
    code = models.CharField(max_length=10)
    price = models.IntegerField()
    y_price = models.IntegerField()
    y_difference = models.IntegerField()
    w_price = models.IntegerField()
    w_differnece = models.IntegerField()
    oneday_tradevolume = models.IntegerField()
    y_tradevolume = models.IntegerField()
    w_tradevolume = models.IntegerField()
    nt_highest = models.IntegerField()
    nt_lowest = models.IntegerField()
    nt_percentage = models.DecimalField(decimal_places=3, max_digits=3)
    tt_highest = models.IntegerField()
    tt_lowest = models.IntegerField()
    tt_percentage = models.DecimalField(decimal_places=3, max_digits=3)
    sales_21 = models.IntegerField()
    operatingincome_21 = models.IntegerField()
    netincome_21 = models.IntegerField()
    sales_20 = models.IntegerField()
    operatingincome_20 = models.IntegerField()
    netincome_20 = models.IntegerField()
    market_cap = models.IntegerField()
    
    
class Corperations(models.Model):
    c_name = models.CharField(max_length=20)
    code = models.CharField(max_length=10)
    

Django/articles/views.py
from sys import excepthook
from django.shortcuts import render, redirect
import pandas as pd
import requests
import simplejson as json
from .models import Corperations, Stocks
import os
import openpyxl
import datetime

windows_user_name = os.path.expanduser('~')

def read_excel(path):
    if path[-1] == 'x':
        try:
            input_data = pd.read_excel(path)
            names = []
            for i in range(len(input_data['회사명'])):
                names.append(input_data['회사명'][i])
            return names
        except Exception as ex:
            print(ex)

    else:
        try:
            input_data = pd.read_csv(path)
            names = []
            for i in range(len(input_data['회사명'])):
                names.append(input_data['회사명'][i])
            return names
        except Exception as ex:
            print(ex)

def get_code(names):
    df = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download', header=0)[0]
    df = df[['회사명', '종목코드']]
    df = df.rename(columns={'회사명': 'Name', '종목코드': 'Code'})

    nc_df = pd.DataFrame(columns=['Name', 'Code'])
    for name in names:
        nc_df = pd.concat([nc_df, df.loc[df['Name'] == name]], ignore_index=True)

    # nc_filter = df['Name'].isin(names)
    # nc_df = df.loc[nc_filter].reset_index(drop=True)
    return nc_df

def get_price(code):
    try:
        url = f'http://finance.daum.net/api/charts/A{code}/days?limit=1000&adjusted=true'
        headers = {'Accept': 'application/json, text/plain, */*', 'Accept-Encoding': 'gzip, deflate',
                   'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7', 'Connection': 'keep-alive',
                   'Cookie': 'GS_font_Name_no=0; GS_font_size=16; _ga=GA1.3.937989519.1493034297; '
                             'webid=bb619e03ecbf4672b8d38a3fcedc3f8c; _ga=GA1.2.937989519.1493034297; '
                             '_gid=GA1.2.215330840.1541556419; KAKAO_STOCK_RECENT=[%22A069500%22]; recentMenus=[{'
                             '%22destination%22:%22chart%22%2C%22title%22:%22%EC%B0%A8%ED%8A%B8%22}%2C{'
                             '%22destination%22:%22current%22%2C%22title%22:%22%ED%98%84%EC%9E%AC%EA%B0%80%22}]; '
                             'TIARA=C-Tax5zAJ3L1CwQFDxYNxe'
                             '-9yt4xuvAcw3IjfDg6hlCbJ_KXLZZhwEPhrMuSc5Rv1oty5obaYZzBQS5Du9ne5x7XZds-vHVF; '
                             'webid_sync=1541565778037; _gat_gtag_UA_128578811_1=1; '
                             '_dfs=VFlXMkVwUGJENlVvc1B3V2NaV1pFdHhpNTVZdnRZTWFZQWZwTzBPYWRxMFNVL3VrODRLY1VlbXI0dHhBZlJzcE03SS9Vblh0U2p2L2V2b3hQbU5mNlE9PS0tcGI2aXQrZ21qY0hFbzJ0S1hkaEhrZz09--6eba3111e6ac36d893bbc58439d2a3e0304c7cf3',
                   'Host': 'finance.daum.net', 'If-None-Match': 'W/"23501689faaaf24452ece4a039a904fd"',
                   'Referer': 'http://finance.daum.net/quotes/A%s' % code,
                   'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) '
                                 'Chrome/70.0.3538.77 Safari/537.36'}
        r = requests.get(url, headers=headers)
        data = json.loads(r.text)
        df = pd.DataFrame(data['data'])
        return df

    except Exception as ex:
        print(ex)


# Create your views here.
def main(request):
    return render(request, 'articles/main.html')

def read_excel(request):
    return render(request, 'articles/read_excel.html')


def read_data(request):
    df = get_price()
    Stock = Stocks()
    stocks = Stocks.objects.all()
    check = Stocks.objects.get[-1]
    n = check.date - datetime.now()
    print(n)
    for i in range(0, n, -1):
        Stock.code = df.iat[-n+i][0]
        Stock.date = df.iat[-n+i][1]
        Stock.tradePrice = df.iat[-n+i][3]
        Stock.candleAccTradeVolume = df.iat[-n+i][8]
        Stock.changePrice = df.iat[-n+i][13]
        Stock.changeRate = df.iat[-n+i][12]
        Stock.save()

    return redirect('articles:main')

def analyzed_data(request):
    return render(request, 'articles/analyzed.html')


def corperations(request):
    corps = Corperations.objects.all()
    context = {
        'corps': corps,
    }
    return render(request, 'articles/corperations/corperations.html', context)

Django/articles/templates/articles/analyzed.html
{% extends 'base.html' %}

{% block content %}
  

{% endblock content %}

Django/articles/templates/articles/corperations/add_corperations.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'articles:add_corperation' %}">
    <label for="companyname">회사명 : </label>
    <input type="text", id="companyname", name="companyname">
    <input type="submit">
  </form>
  <a href="{% url 'articles:main' %}"></a>
{% endblock content %}

Django/articles/templates/articles/corperations/corperations.html
{% extends 'base.html' %}

{% block content %}
  <ul>
    {% for corp in corps %}
      <li>{{ corp.c_name }}</li>
    {% endfor %}
  </ul>

{% endblock content %}

Django/articles/templates/articles/main.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="fs-1 fw-bold">Stock Analysis</h1>

  <a href="{% url 'articles:corperations' %}"><h2>Corperations</h2></a>
  <a href="{% url 'articles:read_excel' %}"><h2>Read Excel</h2></a>
  <a href="{% url 'articles:analyzed_data' %}"><h2>Analyzed Data</h2></a>

{% endblock content %}

Django/articles/templates/articles/read_excel.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="fs-1 fw-bold">READ EXCEL</h1>
  <br>
  <form action="{% url 'articles:read_data' %}">
    <label for="file_path"></label>
    <input type="file" id="file_path" name="file_path">

    <input type="submit">
  </form>
  
  
{% endblock content %}

Django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Stock Analysis</title>
</head>
<body>
  <div class="container">
    {% block content %}
      content default
    {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </div>
</body>
</html>