web/stockdata/urls.py
from django.urls import path
from . import views

app_name = 'stockdata'

urlpatterns = [
    path('', views.main, name='main') ,
    path('<str:corp_code>/', views.detail, name='detail'),
    path('<str:corp_code>/delete', views.delete, name='delete'),

]

web/stockdata/templates/corperations/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="fs-3 fw-bold my-5">{{ corp.c_name }}</h2>

  <div class="container border">
    <div class="row border">
      <div class="col-3">2020_매출</div>
      <div class="col-3">{{ corp.sales_20}}</div>
      <div class="col-3">2021_매출</div>
      <div class="col-3">{{ corp.sales_21 }}</div>
    </div>
    <div class="row border">
      <div class="col-3">2020_영업이익</div>
      <div class="col-3">{{ corp.operatingincome_20 }}</div>
      <div class="col-3">2021_영업이익</div>
      <div class="col-3">{{ corp.operatingincome_21 }}</div>
    </div>
    <div class="row border">
      <div class="col-3">2020_순이익</div>
      <div class="col-3">{{ corp.netincome_20 }}</div>
      <div class="col-3">2021_영업이익</div>
      <div class="col-3">{{ corp.netincome_21 }}</div>
    </div>
    <div class="row border">
      <div class="col-3">시가총액</div>
      <div class="col-3">{{ corp.market_cap }}</div>
      <div class="col-3"></div>
      <div class="col-3"></div>
    </div>
  </div>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="갱신">
  </form>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">회사명</th>
        <th scope="col">회사코드</th>
        <th scope="col">날짜</th>
        <th scope="col">가격</th>
        <th scope="col">거래량</th>
      </tr>
    </thead>
    <tbody>
      {% for corpdate in priceinDate %}
      <tr>
        <td>{{ corp.c_name }}</td>
        <td>{{ corp.c_code }}</td>
        <td>{{ corpdate.date }}</td>
        <td>{{ corpdate.tradePrice }}</td>
        <td>{{ corpdate.volume }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

web/stockdata/templates/corperations/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row d-flex justify-content-end align-items-center">
    <form action="" method="POST">
      {% csrf_token %}
      <div class="d-flex justify-content-end">
        <div class="grid">
          <label for="name">회사명:</label>
          <input type="text" id='name' name='name' placeholder='회사명을 입력하세요..'>
          <label for="code">회사코드:</label>
          <input type="text" id='code' name='code' placeholder='회사 코드' style="width: 100px">
          <input type="submit" value='추가'>
        </div>
      </div>
    </form>
  </div>
  <div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">회사명</th>
          <th scope="col">회사코드</th>
          <th scope="col">현재가격</th>
          <th scope="col">삭제</th>
        </tr>
      </thead>
      <tbody>
        {% for corp in corps %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'stockdata:detail' corp.c_code %}" class="text-decoration-none text-dark">{{ corp.c_name }}</a></td>
            <td>{{ corp.c_code }}</td>
            <td>{{ corp.c_price }}</td>
            <td>
              <form action="{% url 'stockdata:delete' corp.c_code %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="-">
              </form>
          </tr>
        {% endfor %}  
      </tbody>
    </table>
  </div>  
</div>
{% endblock content %}